/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-14 06:53:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1655617123373L));
    _jspx_dependants.put("jar:file:/C:/WithTrip/WithTrip/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/WithTrip/WithTrip/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>WITHTRIP :: 함께라서 좋은 여행</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
      out.write("<!-- <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"> -->\r\n");
      out.write("<!-- <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin> -->\r\n");
      out.write("<!-- <link href=\"https://fonts.googleapis.com/css2?family=Anton&family=Square+Peg&display=swap\" rel=\"stylesheet\"> -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <!-- jQuery -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write(" <!-- iamport.payment.js -->\r\n");
      out.write("<script src =\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("   @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Work+Sans:wght@800&display=swap');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("     padding: 0; \r\n");
      out.write("     margin: 0; \r\n");
      out.write("     box-sizing: border-box; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* body {   */\r\n");
      out.write("/*       padding: 15px;    */\r\n");
      out.write("/* }   */\r\n");
      out.write("\r\n");
      out.write(".container { \r\n");
      out.write("/*       margin: 30px auto;  */\r\n");
      out.write("      max-width: 1000px;  \r\n");
      out.write("/*       background-color: white;   */\r\n");
      out.write("      padding: 0;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("#order_area {\r\n");
      out.write("   margin: 100px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("     height: 25px; \r\n");
      out.write("     width: 150px;\r\n");
      out.write("     border: none; \r\n");
      out.write("     border-radius: 0;\r\n");
      out.write("     font-weight: 800; \r\n");
      out.write("     padding: 0 0 5px 0;\r\n");
      out.write("     background-color: transparent;\r\n");
      out.write("     box-shadow: none;\r\n");
      out.write("     outline: none; \r\n");
      out.write("     border-bottom: 2px solid #ccc;\r\n");
      out.write("     margin: 0;\r\n");
      out.write("     font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus { \r\n");
      out.write("     box-shadow: none;\r\n");
      out.write("     border-bottom: 2px solid #ccc;\r\n");
      out.write("     background-color: transparent;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".form-control2 {\r\n");
      out.write("     font-size: 14px; \r\n");
      out.write("     height: 20px;\r\n");
      out.write("     width: 60px;\r\n");
      out.write("     border: none;\r\n");
      out.write("     border-radius: 0; \r\n");
      out.write("     font-weight: 800; \r\n");
      out.write("     padding: 0 0 5px 0;\r\n");
      out.write("     background-color: transparent;\r\n");
      out.write("     box-shadow: none;\r\n");
      out.write("     outline: none; \r\n");
      out.write("     border-bottom: 2px solid #ccc;\r\n");
      out.write("     margin: 0; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".form-control2:focus { \r\n");
      out.write("     box-shadow: none;\r\n");
      out.write("     border-bottom: 2px solid #ccc; \r\n");
      out.write("     background-color: transparent; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control3 {\r\n");
      out.write("     font-size: 14px; \r\n");
      out.write("     height: 20px; \r\n");
      out.write("     width: 30px; \r\n");
      out.write("     border: none; \r\n");
      out.write("     border-radius: 0; \r\n");
      out.write("     font-weight: 800; \r\n");
      out.write("     padding: 0 0 5px 0; \r\n");
      out.write("     background-color: transparent; \r\n");
      out.write("     box-shadow: none; \r\n");
      out.write("     outline: none; \r\n");
      out.write("     border-bottom: 2px solid #ccc; \r\n");
      out.write("     margin: 0; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".form-control3:focus { \r\n");
      out.write("     box-shadow: none; \r\n");
      out.write("     border-bottom: 2px solid #ccc; \r\n");
      out.write("     background-color: transparent; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("#order_area p {  \r\n");
      out.write("      margin: 0;  \r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("#goodsImg img { \r\n");
      out.write("     width: 100%; \r\n");
      out.write("     height: 100%; \r\n");
      out.write("     object-fit: fill; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".text-muted { \r\n");
      out.write("     font-size: 12px; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".textmuted { \r\n");
      out.write("     color: #6c757d; \r\n");
      out.write("     font-size: 13px; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".fs-14 { \r\n");
      out.write("     font-size: 14px; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("#payBtn { \r\n");
      out.write("     width: 100%; \r\n");
      out.write("     height: 55px; \r\n");
      out.write("     border-radius: 0; \r\n");
      out.write("     padding: 13px 0; \r\n");
      out.write("     background-color: #6495ED; \r\n");
      out.write("     color: #fff;\r\n");
      out.write("     border: none; \r\n");
      out.write("     font-weight: 600; \r\n");
      out.write("     text-align: center;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("#payBtn:hover { \r\n");
      out.write("    background-color: black; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .btn.btn-primary:hover .fas { */\r\n");
      out.write("/*     transform: translateX(10px); */\r\n");
      out.write("/*     transition: transform 0.5s ease */\r\n");
      out.write("/* } */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".fw-900 { \r\n");
      out.write("     font-weight: 900; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("::placeholder { \r\n");
      out.write("     font-size: 12px;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".ps-30 { \r\n");
      out.write("     padding-left: 30px;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".h4 { \r\n");
      out.write("     font-family: 'Work Sans', sans-serif !important; \r\n");
      out.write("     font-weight: 800 !important;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".textmuted, \r\n");
      out.write("h5,\r\n");
      out.write(".text-muted { \r\n");
      out.write("     font-family: 'Poppins', sans-serif; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".pe-1{ */\r\n");
      out.write("    padding : 1px; */\r\n");
      out.write(" } */\r\n");
      out.write("\r\n");
      out.write(".count{ \r\n");
      out.write("    background-color: whitegray; \r\n");
      out.write("    border-bottom: medium;  \r\n");
      out.write("    border-right: medium; \r\n");
      out.write("    border-left: medium; \r\n");
      out.write("    border-top: medium; \r\n");
      out.write("    background-size: 15px; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("#addrBtn {\r\n");
      out.write("   margin-left: 5px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   background: #6496ED;\r\n");
      out.write("   border-radius: 4px;\r\n");
      out.write("   width: 70px;\r\n");
      out.write("   color: white;\r\n");
      out.write("   line-height: 1.5rem;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <!-- header -->   \r\n");
      out.write("   ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"container\" id=\"order_area\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row m-0\">\r\n");
      out.write("            <div class=\"col-lg-7 pb-5 pe-lg-5\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12 p-5\" id=\"goodsImg\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/guploadFiles/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.changeName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"border-radius: 8px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row m-0 bg-light\" style=\"border-radius: 8px;\">\r\n");
      out.write("                        <div class=\"ps-30 my-4\">\r\n");
      out.write("                            <p class=\"fw-bold\">주문자 정보</p><br>\r\n");
      out.write("                     <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\"></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p> <!-- 성함 -->\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\"></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>   <!-- 전화번호 -->\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\"></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>   <!-- 이메일 -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ps-30 pe-0 my-4\">\r\n");
      out.write("                            <p class=\"fw-bold\">배송지 정보</p>\r\n");
      out.write("                     <p class=\"text-muted\" style=\"margin-top: 30px;\">수령인</p>\r\n");
      out.write("                     <input class=\"form-control2\" id=\"recipient\" style=\"width: 130px; height: 20px; color: #464964;\">\r\n");
      out.write("                     <p class=\"text-muted\" style=\"margin-top: 10px;\">연락처</p>\r\n");
      out.write("                     <input class=\"form-control2\" id=\"phone\" style=\"width: 130px; height: 20px; color: #464964;\" onkeyup=\"addHypen(this)\">\r\n");
      out.write("                     \r\n");
      out.write("                     <script type=\"text/javascript\">\r\n");
      out.write("	                     // 하이픈 자동완성\r\n");
      out.write("	                     function addHypen(obj) {\r\n");
      out.write("	                        var number = obj.value.replace(/[^0-9]/g, \"\");\r\n");
      out.write("	                        var phone = \"\";\r\n");
      out.write("	                        \r\n");
      out.write("	                       if(number.length < 4) {\r\n");
      out.write("	                          return number;\r\n");
      out.write("	                       } else if(number.length < 7) {\r\n");
      out.write("	                          phone += number.substr(0, 3);\r\n");
      out.write("	                          phone += \"-\";\r\n");
      out.write("	                          phone += number.substr(3);\r\n");
      out.write("	                       } else if(number.length < 11) {\r\n");
      out.write("	                          phone += number.substr(0, 3);\r\n");
      out.write("	                          phone += \"-\";\r\n");
      out.write("	                          phone += number.substr(3, 3);\r\n");
      out.write("	                          phone += \"-\";\r\n");
      out.write("	                          phone += number.substr(6);\r\n");
      out.write("	                       } else {\r\n");
      out.write("	                          phone += number.substr(0, 3);\r\n");
      out.write("	                          phone += \"-\";\r\n");
      out.write("	                          phone += number.substr(3, 4);\r\n");
      out.write("	                          phone += \"-\";\r\n");
      out.write("	                          phone += number.substr(7);\r\n");
      out.write("	                       }\r\n");
      out.write("	                      obj.value = phone;\r\n");
      out.write("	                     }\r\n");
      out.write("                     </script>\r\n");
      out.write("                     \r\n");
      out.write("                     <div>\r\n");
      out.write("                        <p class=\"text-muted\" style=\"margin-top: 10px;\">우편번호</p>\r\n");
      out.write("                        <input class=\"form-control2\" style=\"width: 100px; height: 20px; color: #464964;\" id=\"zipcode\">\r\n");
      out.write("                               <p class=\"text-muted\" style=\"margin-top: 10px;\">배송 주소</p>   \r\n");
      out.write("                        <input class=\"form-control2\" id=\"address\" style=\"width: 350px; margin-top: 10px; color: #464964;\" readonly>\r\n");
      out.write("                        <button id=\"addrBtn\" style=\"width: 80px; font-size: 12px; margin-left: 20px;\">배송지 변경</button>\r\n");
      out.write("                        <p class=\"text-muted\" style=\"margin-top: 10px;\">상세 주소</p>\r\n");
      out.write("                        <input class=\"form-control2\" id=\"detailAddress\" style=\"width: 350px; height: 20px; color: #464964;\">\r\n");
      out.write("                        <span class=\"fas fa-dollar-sign pe-1\"></span>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-5 p-0 ps-lg-4\">\r\n");
      out.write("                <div class=\"row m-0\">\r\n");
      out.write("                    <div class=\"col-13 px-2\">\r\n");
      out.write("                        <div class=\"d-flex align-items-end mt-4 mb-2\">\r\n");
      out.write("                            <p class=\"h5 m-0\"><span class=\"pe-1\" style=\"font-weight: bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.goodsName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">브랜드</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.goodsBrand }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">배송정보</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\">업체배송</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">배송비</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign px-1\"></span>무료</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-13 px-2\"> \r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">색상</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\"></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.goodsColor }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       <br>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">사이즈</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\"></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.goodsSize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>                 \r\n");
      out.write("                        </div>\r\n");
      out.write("                       <br>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">수량</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\"></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.stock }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개</p>                 \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                     <div class=\"d-flex justify-content-between mb-3\">\r\n");
      out.write("                            <p class=\"textmuted\">결제금액</p>\r\n");
      out.write("                           <div class=\"d-flex align-text-top \">\r\n");
      out.write("                                <span class=\"fas fa-dollar-sign mt-1 pe-1 fs-14 \"></span>\r\n");
      out.write("                                <span id=\"goodsPrice\" class=\"h4\" style=\"color:#6495ED;\"></span>\r\n");
      out.write("                                <span class=\"h4\" style=\"color:#6495ED;\">원</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-sm-13\">\r\n");
      out.write("               </div>\r\n");
      out.write("                    <div class=\"col-12 px-0\">\r\n");
      out.write("                    <br>\r\n");
      out.write("<!--                         <div class=\"row bg-light m-0\" style=\"border-radius: 8px;\"> -->\r\n");
      out.write("<!--                             <div class=\"col-12 px-4 my-4\" > -->\r\n");
      out.write("<!--                                 <p class=\"fw-bold\">카드결제</p> -->\r\n");
      out.write("<!--                             </div> -->\r\n");
      out.write("<!--                             <div class=\"col-12 px-4\"> -->\r\n");
      out.write("<!--                                 <div class=\"d-flex  mb-4\"> -->\r\n");
      out.write("<!--                                     <span class=\"\"> -->\r\n");
      out.write("<!--                                         <p class=\"text-muted\">카드번호</p> -->\r\n");
      out.write("<!--                                         <input class=\"form-control\" type=\"text\" value=\"\" -->\r\n");
      out.write("<!--                                             placeholder=\"1234 5678 9012 3456\"> -->\r\n");
      out.write("<!--                                     </span> -->\r\n");
      out.write("<!--                                     <div class=\" w-100 d-flex flex-column align-items-end\"> -->\r\n");
      out.write("<!--                                         <p class=\"text-muted\">Expires</p> -->\r\n");
      out.write("<!--                                         <input class=\"form-control2\" type=\"text\" value=\"\" placeholder=\"MM/YYYY\"> -->\r\n");
      out.write("<!--                                     </div> -->\r\n");
      out.write("<!--                                 </div> -->\r\n");
      out.write("<!--                                 <div class=\"d-flex mb-5\"> -->\r\n");
      out.write("<!--                                     <span class=\"me-5\"> -->\r\n");
      out.write("<!--                                         <p class=\"text-muted\">카드 소유자 이름</p> -->\r\n");
      out.write("<!--                                         <input class=\"form-control\" type=\"text\" value=\"\"placeholder=\"Name\"> -->\r\n");
      out.write("<!--                                     </span> -->\r\n");
      out.write("<!--                                     <div class=\"w-100 d-flex flex-column align-items-end\"> -->\r\n");
      out.write("<!--                                         <p class=\"text-muted\">CVC</p> -->\r\n");
      out.write("<!--                                         <input class=\"form-control3\" type=\"text\" value=\"\" placeholder=\"XXX\"> -->\r\n");
      out.write("<!--                                     </div> -->\r\n");
      out.write("<!--                                 </div> -->\r\n");
      out.write("<!--                             </div>                           -->\r\n");
      out.write("<!--                         </div> -->\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div id=\"payBtn\" style=\"border-radius: 8px;\">결제하기\r\n");
      out.write("                        </div>\r\n");
      out.write("                  \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("   <!-- footer -->\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("   <script>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("//        console.log($(\"#zipcode\").val());\r\n");
      out.write("        var pay = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("        console.log(pay);\r\n");
      out.write("        \r\n");
      out.write("        var IMP = window.IMP;\r\n");
      out.write("        // 가맹점 식별코드\r\n");
      out.write("        IMP.init(\"imp31950016\");\r\n");
      out.write("        var msg;\r\n");
      out.write("        \r\n");
      out.write("        $(\"#payBtn\").click(function(){\r\n");
      out.write("        	\r\n");
      out.write("        	 if($('#recipient').val().trim() == '') {\r\n");
      out.write("         		 alert('수령인을 입력하세요.');\r\n");
      out.write("         		 $('#recipient').focus();\r\n");
      out.write("         		 return false;\r\n");
      out.write("         	 } else if($('#phone').val().trim() == '') {\r\n");
      out.write("         		 alert('연락처를 입력하세요');\r\n");
      out.write("         		 $('#phone').focus(); \r\n");
      out.write("         		 return false;\r\n");
      out.write("         	 } else if($('#zipcode').val().trim() == '') {\r\n");
      out.write("         		 alert('우편번호를 입력하세요');\r\n");
      out.write("         		 $('#zipcode').focus(); \r\n");
      out.write("         		 return false\r\n");
      out.write("         	 } else if($('#address').val().trim() == '') {\r\n");
      out.write("         		 alert('배송 주소를 입력하세요');\r\n");
      out.write("         		 $('#address').focus(); \r\n");
      out.write("         		 return false;\r\n");
      out.write("           	 } else if($('#detailAddress').val().trim() == '') {\r\n");
      out.write("         		 alert('상세 주소를 입력하세요');\r\n");
      out.write("         		 $('#detailAddress').focus(); \r\n");
      out.write("         		 return false;\r\n");
      out.write("         	 }\r\n");
      out.write("         	 \r\n");
      out.write("            var postcode = document.querySelector('#zipcode').value;\r\n");
      out.write("			var phone = document.querySelector('#phone').value;\r\n");
      out.write("			var address = document.querySelector('#address').value;\r\n");
      out.write("			var detailAddress = document.querySelector('#detailAddress').value;\r\n");
      out.write("			var orderAddress = address + \" / \" + detailAddress;\r\n");
      out.write("			\r\n");
      out.write("           // 결제 요청\r\n");
      out.write("           IMP.request_pay({  // 보낼 정보, param\r\n");
      out.write("	            pay_method : 'card',\r\n");
      out.write("	            merchant_uid : 'w' + new Date().getTime(),            \r\n");
      out.write("	            name : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.goodsName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("// 	            amount : 150000,\r\n");
      out.write("	            amount : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("	            buyer_email : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("	            buyer_name : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("	            buyer_tel : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("	            buyer_addr: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("	            buyer_postcode : $(\"#zipcode\").val(),\r\n");
      out.write("	            receipt_url : null\r\n");
      out.write("           }, function(rsp){ // callback 함수  (-->다른 함수의 인자로써 넘겨진 후 특정 이벤트에 의해 호출되는 함수)\r\n");
      out.write("//               if(rsp.success) { // 결제 성공 시 \r\n");
      out.write("//             	  console.log(rsp);\r\n");
      out.write("            	  var impUid = rsp.imp_uid;\r\n");
      out.write("            	  console.log(impUid);\r\n");
      out.write("            	  \r\n");
      out.write("	            	// 결제 검증 및 결제(DB 저장 포함)\r\n");
      out.write("	      			$.ajax({\r\n");
      out.write("	      	        	type : \"POST\",\r\n");
      out.write("	      	        	data: { imp_uid:impUid },\r\n");
      out.write("	      	        	url : \"verifyIamport.od\"\r\n");
      out.write("	      	        }).done(function(data) {\r\n");
      out.write("	      	        	\r\n");
      out.write("						console.log(data);\r\n");
      out.write("						console.log(rsp.paid_amount);\r\n");
      out.write("						console.log(data.response.amount);\r\n");
      out.write("	      	        	\r\n");
      out.write("	      	        	// 위의 rsp.paid_amount 와 data.response.amount를 비교한후 결제 로직 실행 (iamport 서버 검증)\r\n");
      out.write("				        if(rsp.paid_amount == data.response.amount){\r\n");
      out.write("	            	  \r\n");
      out.write("				                 var msg = '결제가 완료되었습니다.';\r\n");
      out.write("				                 var result = {\r\n");
      out.write("				                  	// order 테이블에 보낼 정보\r\n");
      out.write("									\"orderNo\" : rsp.merchant_uid, // 주문번호\r\n");
      out.write("									\"price\" : rsp.paid_amount, // 주문금액\r\n");
      out.write("									\"orderAddress\" : orderAddress,\r\n");
      out.write("									\"zipCode\" : postcode,\r\n");
      out.write("									\"shipNo\" : 'shipNo_' + new Date().getTime(),\r\n");
      out.write("									\"recipient\" : $(\"#recipient\").val(),\r\n");
      out.write("									\"email\" : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("									\"goodsId\" : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.goodsId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("									\"payNO\" : rsp.imp_uid,\r\n");
      out.write("									\"approvalNo\" : rsp.apply_num, // 승인 번호(?)\r\n");
      out.write("									\"phone\" : $('#phone').val(),\r\n");
      out.write("									\"receiptUrl\" : rsp.receipt_url \r\n");
      out.write("				                 }\r\n");
      out.write("				                 \r\n");
      out.write("				                 console.log(\"결제 성공\" + msg);\r\n");
      out.write("				                 \r\n");
      out.write("				                 $.ajax({\r\n");
      out.write("				                    url: \"payment.od\",\r\n");
      out.write("				                    type : \"POST\",\r\n");
      out.write("				                    dataType : 'json',\r\n");
      out.write("				                    data : JSON.stringify(result,\r\n");
      out.write("				                          ['phone', 'orderNo', 'price', 'recipient', 'shipNo', 'orderAddress', 'zipCode', 'card_no', 'orderStatus', 'email', 'goodsId', 'payNO','approvalNo', 'receiptUrl']),\r\n");
      out.write("				                    contentType : 'application/json;charset=utf-8',\r\n");
      out.write("				                    success: function(res) {	// 결제 및 DB 저장 성공 시 data==1 / 실패 시  0\r\n");
      out.write("				                    	\r\n");
      out.write("				                       if(res == 1) {\r\n");
      out.write("				                          console.log(\"결제 및 DB 저장 성공\");\r\n");
      out.write("				                          alert('결제되었습니다.');\r\n");
      out.write("// 						              			alert(\"결제 및 결제검증완료\");\r\n");
      out.write("				                          var goodsId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ g.goodsId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("				                          var orderNo = rsp.merchant_uid;\r\n");
      out.write("				                          document.location.href=\"paymentDetail.od?orderNo=\" + orderNo + \"&goodsId=\" + goodsId;\r\n");
      out.write("				                       } else {\r\n");
      out.write("				                          console.log(\"통신 실패\");\r\n");
      out.write("				                       }\r\n");
      out.write("				                       \r\n");
      out.write("				                    }, // success\r\n");
      out.write("				                    error: function() {\r\n");
      out.write("				                    	console.log(\"결제 실패\");\r\n");
      out.write("				                    } // error\r\n");
      out.write("				                 }); // 결제 로직 ajax\r\n");
      out.write("			                  \r\n");
      out.write("	      	        	} else {	// iamport 서버 검증에 만족하지 못 했을 때\r\n");
      out.write("	      	        		alert(\"검증 실패\");\r\n");
      out.write("	      	        	}\r\n");
      out.write("	      	        });\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("//               } else { // 결제 실패 시 \r\n");
      out.write("// //                  var msg = \"결제에 실패하였습니다.\";\r\n");
      out.write("//                  var msg = \"결제 및 검증에 실패하였습니다.\";\r\n");
      out.write("//                  msg += '에러남' + rsp.error_msg; \r\n");
      out.write("//                  console.log(msg);\r\n");
      out.write("//               }\r\n");
      out.write("           \r\n");
      out.write("           }); // 결제 요청\r\n");
      out.write("        });	// 결제 버튼 클릭 이벤트\r\n");
      out.write("     }); // $(document).ready() 이벤트\r\n");
      out.write("    \r\n");
      out.write("         // 결제금액에 콤마 찍기\r\n");
      out.write("         $(document).ready(function(){\r\n");
      out.write("//             console.log(typeof ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${g.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\r\n");
      out.write("            var gPrice = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${g.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("            var priceComma = gPrice.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',');\r\n");
      out.write("         $(\"#goodsPrice\").text(priceComma);\r\n");
      out.write("//             console.log(typeof priceComma);\r\n");
      out.write("         \r\n");
      out.write("//          var goodsPrice = parseInt($(\"#goodsPrice\").text().replace(\",\", \"\"));\r\n");
      out.write("//          console.log(typeof goodsPrice);\r\n");
      out.write("//             $(\"#price\").val(goodsPrice);\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("          // 주소 input을 클릭하면 카카오맵 팝업창 실행\r\n");
      out.write("          $('#addrBtn').on('click', function(){\r\n");
      out.write("              new daum.Postcode({\r\n");
      out.write("                  oncomplete: function(data) {\r\n");
      out.write("                    // 팝업에서 검색 결과 주소를 클릭 했을 때 주소 input칸에 입력되게 함 \r\n");
      out.write("                      document.querySelector('#address').value = data.address;\r\n");
      out.write("                      document.querySelector('#zipcode').value = data.zonecode;\r\n");
      out.write("                      document.getElementById(\"detailAddress\").focus();\r\n");
      out.write("                  }\r\n");
      out.write("              }).open();\r\n");
      out.write("          });\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("</script>       \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/order/order.jsp(212,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/navbar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/order/order.jsp(377,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../common/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
