/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-10 13:20:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class totalManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1655617123373L));
    _jspx_dependants.put("jar:file:/C:/WithTrip/WithTrip/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>WITHTRIP :: 함께라서 좋은 여행</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"resources/vendor3/bootstrap/css/bootstrap_admin.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template -->\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Grape+Nuts&family=Noto+Sans+KR:wght@300&family=Raleway:wght@100;&family=Titillium+Web&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"resources/css3/admin.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/dd62c289ec.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 탑버튼 -->    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js\" integrity=\"sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("  body{\r\n");
      out.write("  	background: #fafafa !important;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write(".pageRound{\r\n");
      out.write("	margin-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write(".prdload{\r\n");
      out.write("	margin-left: 20%;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".prdArea{\r\n");
      out.write("	margin-left: 20%;\r\n");
      out.write("	width: 700px;\r\n");
      out.write("   height: 400px;\r\n");
      out.write("	border: 1px solid #eee;\r\n");
      out.write("	background : #fff;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("}\r\n");
      out.write("* {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  -moz-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul { list-style-type: none; }\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("  color: #b63b4d;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".accordion {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 384px;\r\n");
      out.write("    margin: 30px auto 20px;\r\n");
      out.write("    background: none;\r\n");
      out.write("    -webkit-border-radius: 4px;\r\n");
      out.write("    -moz-border-radius: 4px;\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("    margin-left: -16px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accordion .link {\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding: 15px 15px 15px 42px;\r\n");
      out.write("  color: #4D4D4D;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  border-bottom: 1px solid #CCC;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  -webkit-transition: all 0.4s ease;\r\n");
      out.write("  -o-transition: all 0.4s ease;\r\n");
      out.write("  transition: all 0.4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accordion li:last-child .link { border-bottom: 0; }\r\n");
      out.write("\r\n");
      out.write(".accordion li i {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 16px;\r\n");
      out.write("  left: 12px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  color: #595959;\r\n");
      out.write("  -webkit-transition: all 0.4s ease;\r\n");
      out.write("  -o-transition: all 0.4s ease;\r\n");
      out.write("  transition: all 0.4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accordion li.link { color: #000; font-weight: bold; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#prdnav{\r\n");
      out.write(" width: 20rem;\r\n");
      out.write(" background-image: linear-gradient(to right, #74ebd5 0%, #9face6 100%);\r\n");
      out.write(" border: 1px solid #ddd;\r\n");
      out.write("  position : fixed; \r\n");
      out.write(" height : 100%;\r\n");
      out.write(" border-bottom-right-radius: 10px;\r\n");
      out.write(" color : #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myChart{\r\n");
      out.write("	max-width : 400px;\r\n");
      out.write("	max-height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".totalArea{\r\n");
      out.write("	width: 500px;\r\n");
      out.write("    height: 300px;\r\n");
      out.write("    border: 1px solid #eee;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border-radius: 7px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("	margin-left: 57.5%;\r\n");
      out.write("    margin-top: -26%;\r\n");
      out.write("    padding: 50px;\r\n");
      out.write("    padding-top: 72px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#todayTotal{\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	margin-bottom: 100px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: #4f5d75;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#todayWon{\r\n");
      out.write("	font-size: 40px;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	color : #6495ED;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	font-family: 'Comfortaa', cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cateGrahp{\r\n");
      out.write("	width: 700px;\r\n");
      out.write("    height: 420px;\r\n");
      out.write("    border: 1px solid #eee;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border-radius: 7px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 20%;\r\n");
      out.write("    margin-top: -80px;\r\n");
      out.write("    padding: 35px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("}\r\n");
      out.write("#pie-chart{\r\n");
      out.write(" max-width: 300px;\r\n");
      out.write(" max-height: 300px;\r\n");
      out.write(" margin: auto;\r\n");
      out.write(" margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#percent{\r\n");
      out.write("	background-image: radial-gradient(circle 248px at center, #16d9e3 0%, #30c7ec 47%, #46aef7 100%);\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	color : #fff;\r\n");
      out.write("	width: 160px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topten{\r\n");
      out.write("	width: 500px;\r\n");
      out.write("    height: 530px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	border: 1px solid #eee;\r\n");
      out.write("    position: absolute;\r\n");
      out.write(" 	margin-left: 57.5%;\r\n");
      out.write("    margin-top: -9.4%;\r\n");
      out.write(" 	color : #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#firstCol{\r\n");
      out.write("	width: 50px;\r\n");
      out.write("}\r\n");
      out.write("#topten{\r\n");
      out.write("	height: 510px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topten th{\r\n");
      out.write("	font-family: 'Comfortaa', cursive;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topTableTitle{\r\n");
      out.write("\r\n");
      out.write("text-align: center; width: 500px; color: #4f5d75; font-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("  <!-- navbar -->\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("<!-- sideNav -->\r\n");
      out.write("			<nav  id=\"prdnav\">\r\n");
      out.write("				<ul id=\"accordion\" class=\"accordion\">\r\n");
      out.write("					<li style=\"text-align: center; color:#000; font-weight: bold; margin-bottom: 30px;\">관리자 대시보드</li>\r\n");
      out.write("				  <li>\r\n");
      out.write("				    <div class=\"link\" onclick=\"location.href='prdManage.ad';\"><i class=\"fa-solid fa-suitcase-rolling\"></i>상품관리</div>\r\n");
      out.write("				  </li>\r\n");
      out.write("				  <li>\r\n");
      out.write("				    <div class=\"link\" style=\"font-weight: 900; color: #000;\" onclick=\"location.href='orderManage.ad';\"  ><i class=\"fa-solid fa-receipt\" ></i>주문관리</div>\r\n");
      out.write("				  </li>\r\n");
      out.write("				  <li>\r\n");
      out.write("				    <div class=\"link\" onclick=\"location.href='totalManage.ad';\" style=\"margin-bottom: 150px;\"><i class=\"fa-solid fa-arrow-trend-up\"></i>통계분석</div>\r\n");
      out.write("				  </li>\r\n");
      out.write("				</ul>\r\n");
      out.write("            </nav> \r\n");
      out.write("        <!-- sideNav -->\r\n");
      out.write("        \r\n");
      out.write("	<div class=\"pageRound\">\r\n");
      out.write("		<div class=\"prdload\">\r\n");
      out.write("		        <a onclick=\"location.href='adminManage.ad';\">관리자페이지</a> > <a style=\"font-weight: bold;\" onclick=\"location.href='prd_manage.ad';\">상품관리</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"prdArea\"> \r\n");
      out.write("			<div>\r\n");
      out.write("  				<canvas id=\"line-chart\" width=\"250\" max-height=\"300\" ></canvas>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"totalArea\">\r\n");
      out.write("		<a id=\"todayTotal\">금일 매출 현황</a><br>\r\n");
      out.write("		<a id=\"todayWon\">\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</a><span style=\"font-weight: bold; font-size: 25px; color: #4f5d75;\">원</span>\r\n");
      out.write("		<div id=\"percent\">전일 대비 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ variance }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("% 증가</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"cateGrahp\">\r\n");
      out.write("		<div>\r\n");
      out.write("  			<div class =\"piechart\"><canvas id=\"pie-chart\" width=\"250\" height=\"250\"></canvas>\r\n");
      out.write("  			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("  			 <a>가방 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", 안전용품  : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cate2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", 악세사리 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </a>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"topten\" style=\"papping:\">\r\n");
      out.write("		<table id=\"topten\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"2\" id=\"topTableTitle\">누적 주문 TOP10</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("<!-- 		<tr> -->\r\n");
      out.write("<!-- 			<th></th> -->\r\n");
      out.write("<!-- 			<td></td> -->\r\n");
      out.write("<!-- 		</tr> -->\r\n");
      out.write("		</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function topList(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: 'topList.ad',\r\n");
      out.write("			success : function(data){\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				\r\n");
      out.write("				$tableBody = $('#topten tbody');\r\n");
      out.write("				$tableBody.html('');\r\n");
      out.write("				for(var i in data){\r\n");
      out.write("					var $tr = $('<tr>');\r\n");
      out.write("					var $no = $('<th>').text(1 + parseInt(i));\r\n");
      out.write("					var $goodsName = $('<td>').text(data[i].goodsName);\r\n");
      out.write("					\r\n");
      out.write("					$tr.append($no).append($goodsName);\r\n");
      out.write("					$tableBody.append($tr);\r\n");
      out.write("					\r\n");
      out.write("					console.log($tr);\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(data){\r\n");
      out.write("				console.log(data);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<!--  chart.js -->\r\n");
      out.write("<script>\r\n");
      out.write("new Chart(document.getElementById(\"pie-chart\"), {\r\n");
      out.write("    type: 'pie',\r\n");
      out.write("    data: {\r\n");
      out.write("      labels: [\"가방\", \"안전용품\", \"악세사리\"],\r\n");
      out.write("      datasets: [{\r\n");
      out.write("        backgroundColor: [\"#ff1b8d\", \"#ffd900\",\"#1bb2ff\"],\r\n");
      out.write("        data: ['");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' , '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("']\r\n");
      out.write("      }]\r\n");
      out.write("    },\r\n");
      out.write("    options: {\r\n");
      out.write("      title: {\r\n");
      out.write("        display: true,\r\n");
      out.write("        text: '카테고리별 주문건수'\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	let amount = [];\r\n");
      out.write("	let month = [];\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"monthamount.ad\",\r\n");
      out.write("		success : function(data){\r\n");
      out.write("			\r\n");
      out.write("			for(var i in data){\r\n");
      out.write("				amount.push(data[i].amount);\r\n");
      out.write("				month.push(data[i].month);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			new Chart(document.getElementById(\"line-chart\"), {\r\n");
      out.write("			    type: 'line',\r\n");
      out.write("			    data: {\r\n");
      out.write("			      labels: month,\r\n");
      out.write("			      datasets: [{\r\n");
      out.write("			   	  label : '매출액',\r\n");
      out.write("		    	  borderColor: \"rgba(255, 191, 0, 1)\",\r\n");
      out.write("		          backgroundColor: \"rgba(255, 213, 87, 0.82)\",\r\n");
      out.write("		          data: amount,\r\n");
      out.write("		      }]\r\n");
      out.write("		    },\r\n");
      out.write("		    options: {\r\n");
      out.write("		      title: {\r\n");
      out.write("		        display: true,\r\n");
      out.write("		        text: '월별 매출액'\r\n");
      out.write("		      }\r\n");
      out.write("		      }\r\n");
      out.write("		});\r\n");
      out.write("		},\r\n");
      out.write("		\r\n");
      out.write("		error : function(data) {\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("// 결제금액에 콤마 찍기\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("//    console.log(typeof ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${g.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\r\n");
      out.write("   var totaltoday = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ totaltoday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("   var totaltodayComma = totaltoday.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',');\r\n");
      out.write("$(\"#todayWon\").text(totaltodayComma);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/admin/totalManage.jsp(226,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/navbar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/admin/totalManage.jsp(259,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totaltoday eq '0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		0\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/admin/totalManage.jsp(262,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totaltoday ne '0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ totaltoday }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
